# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: Java CI with Gradle # Workflow 이름

on: # Event 감지
  push:
    branches: [ main ] # main 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻
  pull_request:
    branches: [ main ] 

permissions:
  contents: read

jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11 # JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle # Gradle Build
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
     
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/
        
      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./cola_back.zip ./deploy

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          ./deploy/cola_back.zip s3://cola-deploy/deploy/cola_back.zip
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name deployApp
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cola
          --s3-location bucket=cola-deploy,key=./deploy/cola_back.zip ,bundleType=zip
